<?php

declare(strict_types=1);

namespace Ilbee\Okta\Event\Service;

use Ilbee\Okta\Event\DTO\OktaEvent;
use Ilbee\Okta\Event\Event;
use Ilbee\Okta\Event\Event\GenericOktaEvent;

/**
 * Maps Okta event type IDs to their corresponding PHP event classes.
 *
 * Provides both individual event classes (one per Okta event type)
 * and group event classes (one per Okta event category).
 */
final readonly class OktaEventRegistry
{
    /**
     * Maps Okta event type IDs to individual event classes.
     * Events not in this map have existing typed classes handled by OktaEventMapper.
     *
     * @var array<string, class-string<GenericOktaEvent>>
     */
    private const INDIVIDUAL_EVENTS = [
        'access.request.create' => Event\AccessRequest\OktaAccessRequestCreatedEvent::class,
        'access.request.resolve' => Event\AccessRequest\OktaAccessRequestResolvedEvent::class,
        'access.request.cancel' => Event\AccessRequest\OktaAccessRequestCanceledEvent::class,
        'access.request.expire' => Event\AccessRequest\OktaAccessRequestExpiredEvent::class,
        'access.request.reject' => Event\AccessRequest\OktaAccessRequestRejectedEvent::class,
        'access.request.sequence.create' => Event\AccessRequest\OktaAccessRequestSequenceCreatedEvent::class,
        'access.request.sequence.update' => Event\AccessRequest\OktaAccessRequestSequenceUpdatedEvent::class,
        'access.request.sequence.delete' => Event\AccessRequest\OktaAccessRequestSequenceDeletedEvent::class,
        'access.request.condition.create' => Event\AccessRequest\OktaAccessRequestConditionCreatedEvent::class,
        'access.request.condition.update' => Event\AccessRequest\OktaAccessRequestConditionUpdatedEvent::class,
        'access.request.condition.delete' => Event\AccessRequest\OktaAccessRequestConditionDeletedEvent::class,
        'access.request.condition.activate' => Event\AccessRequest\OktaAccessRequestConditionActivatedEvent::class,
        'access.request.condition.deactivate' => Event\AccessRequest\OktaAccessRequestConditionDeactivatedEvent::class,
        'access.request.condition.invalidate' => Event\AccessRequest\OktaAccessRequestConditionInvalidatedEvent::class,
        'access.request.settings.update' => Event\AccessRequest\OktaAccessRequestSettingsUpdatedEvent::class,
        'system.idp.key.create' => Event\IdpKey\OktaIdpKeyCreatedEvent::class,
        'system.idp.key.update' => Event\IdpKey\OktaIdpKeyUpdatedEvent::class,
        'system.idp.key.delete' => Event\IdpKey\OktaIdpKeyDeletedEvent::class,
        'user.account.subscriptions.update' => Event\UserAccountSubscription\OktaUserAccountSubscriptionUpdatedEvent::class,
        'application.lifecycle.activate' => Event\ApplicationLifecycle\OktaApplicationActivatedEvent::class,
        'application.lifecycle.create' => Event\ApplicationLifecycle\OktaApplicationCreatedEvent::class,
        'application.lifecycle.deactivate' => Event\ApplicationLifecycle\OktaApplicationDeactivatedEvent::class,
        'application.lifecycle.delete' => Event\ApplicationLifecycle\OktaApplicationDeletedEvent::class,
        'application.lifecycle.update' => Event\ApplicationLifecycle\OktaApplicationUpdatedEvent::class,
        'group.lifecycle.create' => Event\GroupLifecycle\OktaGroupCreatedEvent::class,
        'group.lifecycle.delete' => Event\GroupLifecycle\OktaGroupDeletedEvent::class,
        'system.import.group.create' => Event\GroupLifecycle\OktaImportGroupCreatedEvent::class,
        'system.import.group.delete' => Event\GroupLifecycle\OktaImportGroupDeletedEvent::class,
        'certification.campaign.launch' => Event\Certification\OktaCertificationCampaignLaunchedEvent::class,
        'certification.campaign.close' => Event\Certification\OktaCertificationCampaignClosedEvent::class,
        'certification.campaign.item.decide' => Event\Certification\OktaCertificationItemDecidedEvent::class,
        'certification.campaign.item.remediate' => Event\Certification\OktaCertificationItemRemediatedEvent::class,
        'certification.campaign.context.update' => Event\Certification\OktaCertificationContextUpdatedEvent::class,
        'group.profile.update' => Event\Group\OktaGroupProfileUpdatedEvent::class,
        'group.application_assignment.remove' => Event\Group\OktaGroupAppAssignmentRemovedEvent::class,
        'group.application_assignment.add' => Event\Group\OktaGroupAppAssignmentAddedEvent::class,
        'group.application_assignment.update' => Event\Group\OktaGroupAppAssignmentUpdatedEvent::class,
        'system.org.rate_limit.warning' => Event\RateLimit\OktaRateLimitWarningEvent::class,
        'system.org.rate_limit.violation' => Event\RateLimit\OktaRateLimitViolationEvent::class,
        'app.access_request.request' => Event\UserApp\OktaAppAccessRequestedEvent::class,
        'app.access_request.approver.approve' => Event\UserApp\OktaAppAccessApprovedEvent::class,
        'app.access_request.approver.deny' => Event\UserApp\OktaAppAccessDeniedByApproverEvent::class,
        'app.access_request.expire' => Event\UserApp\OktaAppAccessExpiredEvent::class,
        'app.access_request.delete' => Event\UserApp\OktaAppAccessDeletedEvent::class,
        'app.access_request.grant' => Event\UserApp\OktaAppAccessGrantedEvent::class,
        'app.access_request.deny' => Event\UserApp\OktaAppAccessDeniedEvent::class,
        'application.user_membership.change_password' => Event\UserApp\OktaAppUserPasswordChangedEvent::class,
        'application.user_membership.update' => Event\UserApp\OktaAppUserUpdatedEvent::class,
        'application.provision.user.sync' => Event\UserApp\OktaAppUserSyncedEvent::class,
        'application.provision.user.import_profile' => Event\UserApp\OktaAppUserProfileImportedEvent::class,
        'application.provision.user.push' => Event\UserApp\OktaAppUserPushedEvent::class,
        'application.provision.user.push_profile' => Event\UserApp\OktaAppUserProfilePushedEvent::class,
        'application.provision.user.reactivate' => Event\UserApp\OktaAppUserReactivatedEvent::class,
        'app.interclient_mapping.create' => Event\UserApp\OktaInterclientMappingCreatedEvent::class,
        'app.interclient_mapping.delete' => Event\UserApp\OktaInterclientMappingDeletedEvent::class,
        'app.interclient_mapping.delete_all' => Event\UserApp\OktaInterclientMappingAllDeletedEvent::class,
        'app.oauth2.as.consent.grant' => Event\UserApp\OktaOAuth2ConsentGrantedEvent::class,
        'app.oauth2.as.consent.revoke' => Event\UserApp\OktaOAuth2ConsentRevokedEvent::class,
        'app.oauth2.as.consent.revoke.implicit.as' => Event\UserApp\OktaOAuth2ConsentRevokedForServerEvent::class,
        'app.oauth2.as.consent.revoke.implicit.client' => Event\UserApp\OktaOAuth2ConsentRevokedForClientEvent::class,
        'app.oauth2.as.consent.revoke.implicit.scope' => Event\UserApp\OktaOAuth2ConsentRevokedForScopeEvent::class,
        'app.oauth2.as.consent.revoke.implicit.user' => Event\UserApp\OktaOAuth2ConsentRevokedForUserScopesEvent::class,
        'app.oauth2.as.consent.revoke.user' => Event\UserApp\OktaOAuth2ConsentRevokedAllForUserEvent::class,
        'app.oauth2.as.consent.revoke.user.client' => Event\UserApp\OktaOAuth2ConsentRevokedUserClientEvent::class,
        'app.oauth2.as.token.grant.interclient_token' => Event\UserApp\OktaOAuth2InterclientTokenGrantedEvent::class,
        'app.oauth2.token.grant.interclient_token' => Event\UserApp\OktaOAuth2TokenInterclientGrantedEvent::class,
        'entitlement.migration.start' => Event\EntitlementMigration\OktaEntitlementMigrationStartedEvent::class,
        'entitlement.migration.complete' => Event\EntitlementMigration\OktaEntitlementMigrationCompletedEvent::class,
        'entitlement.migration.fail' => Event\EntitlementMigration\OktaEntitlementMigrationFailedEvent::class,
        'user.account.privilege.grant' => Event\AdminPrivilege\OktaUserPrivilegeGrantedEvent::class,
        'user.account.privilege.revoke' => Event\AdminPrivilege\OktaUserPrivilegeRevokedEvent::class,
        'group.privilege.grant' => Event\AdminPrivilege\OktaGroupPrivilegeGrantedEvent::class,
        'group.privilege.revoke' => Event\AdminPrivilege\OktaGroupPrivilegeRevokedEvent::class,
        'app.oauth2.client.privilege.grant' => Event\AdminPrivilege\OktaOAuth2ClientPrivilegeGrantedEvent::class,
        'app.oauth2.client.privilege.revoke' => Event\AdminPrivilege\OktaOAuth2ClientPrivilegeRevokedEvent::class,
        'iam.role.create' => Event\AdminPrivilege\OktaIamRoleCreatedEvent::class,
        'iam.role.delete' => Event\AdminPrivilege\OktaIamRoleDeletedEvent::class,
        'iam.role.update' => Event\AdminPrivilege\OktaIamRoleUpdatedEvent::class,
        'iam.role.permissions.add' => Event\AdminPrivilege\OktaIamRolePermissionsAddedEvent::class,
        'iam.role.permissions.delete' => Event\AdminPrivilege\OktaIamRolePermissionsDeletedEvent::class,
        'iam.role.permission.conditions.add' => Event\AdminPrivilege\OktaIamPermissionConditionsAddedEvent::class,
        'iam.role.permission.conditions.delete' => Event\AdminPrivilege\OktaIamPermissionConditionsDeletedEvent::class,
        'iam.resourceset.create' => Event\AdminPrivilege\OktaIamResourceSetCreatedEvent::class,
        'iam.resourceset.delete' => Event\AdminPrivilege\OktaIamResourceSetDeletedEvent::class,
        'iam.resourceset.update' => Event\AdminPrivilege\OktaIamResourceSetUpdatedEvent::class,
        'iam.resourceset.resources.add' => Event\AdminPrivilege\OktaIamResourceSetResourcesAddedEvent::class,
        'iam.resourceset.resources.update' => Event\AdminPrivilege\OktaIamResourceSetResourcesUpdatedEvent::class,
        'iam.resourceset.resources.delete' => Event\AdminPrivilege\OktaIamResourceSetResourcesDeletedEvent::class,
        'iam.resourceset.bindings.add' => Event\AdminPrivilege\OktaIamResourceSetBindingsAddedEvent::class,
        'iam.resourceset.bindings.delete' => Event\AdminPrivilege\OktaIamResourceSetBindingsDeletedEvent::class,
        'iam.policy.configuration.update' => Event\AdminPrivilege\OktaIamPolicyConfigurationUpdatedEvent::class,
        'iam.policy.assignee_configuration.update' => Event\AdminPrivilege\OktaIamPolicyAssigneeConfigurationUpdatedEvent::class,
        'system.api_token.create' => Event\UserAuth\OktaApiTokenCreatedEvent::class,
        'system.api_token.revoke' => Event\UserAuth\OktaApiTokenRevokedEvent::class,
        'system.voice.send_phone_verification_call' => Event\UserAuth\OktaPhoneVerificationCallSentEvent::class,
        'system.mfa.preregister.initiate' => Event\UserAuth\OktaMfaPreregisterInitiatedEvent::class,
        'user.authentication.auth_via_mfa' => Event\UserAuth\OktaUserAuthViaMfaEvent::class,
        'user.mfa.factor.activate' => Event\UserAuth\OktaUserMfaFactorActivatedEvent::class,
        'user.mfa.factor.deactivate' => Event\UserAuth\OktaUserMfaFactorDeactivatedEvent::class,
        'user.mfa.factor.suspend' => Event\UserAuth\OktaUserMfaFactorSuspendedEvent::class,
        'user.mfa.factor.unsuspend' => Event\UserAuth\OktaUserMfaFactorUnsuspendedEvent::class,
        'user.mfa.factor.update' => Event\UserAuth\OktaUserMfaFactorUpdatedEvent::class,
        'user.mfa.factor.reset_all' => Event\UserAuth\OktaUserMfaFactorResetAllEvent::class,
        'user.session.clear' => Event\UserAuth\OktaUserSessionClearedEvent::class,
        'user.account.reset_password' => Event\UserAuth\OktaUserAccountPasswordResetEvent::class,
        'user.account.unlock' => Event\UserAuth\OktaUserAccountUnlockedEvent::class,
        'user.account.unlock_by_admin' => Event\UserAuth\OktaUserAccountUnlockedByAdminEvent::class,
        'user.account.update_password' => Event\UserAuth\OktaUserAccountPasswordUpdatedEvent::class,
        'application.policy.sign_on.deny_access' => Event\UserAuth\OktaAppSignOnDeniedEvent::class,
        'user.authentication.auth_via_IDP' => Event\UserAuth\OktaUserAuthViaIdpEvent::class,
        'user.authentication.auth_via_social' => Event\UserAuth\OktaUserAuthViaSocialEvent::class,
        'system.sms.send_phone_verification_message' => Event\UserAuth\OktaPhoneVerificationSmsSentEvent::class,
        'user.session.start' => Event\UserAuth\OktaUserSessionStartedEvent::class,
        'user.session.end' => Event\UserAuth\OktaUserSessionEndedEvent::class,
        'user.authentication.universal_logout' => Event\UserAuth\OktaUserUniversalLogoutEvent::class,
        'user.authentication.universal_logout.scheduled' => Event\UserAuth\OktaUserUniversalLogoutScheduledEvent::class,
        'user.account.lock' => Event\UserAuth\OktaUserAccountLockedEvent::class,
        'user.identity_verification' => Event\UserAuth\OktaUserIdentityVerificationEvent::class,
        'user.identity_verification.start' => Event\UserAuth\OktaUserIdentityVerificationStartedEvent::class,
        'user.import.password' => Event\UserAuth\OktaUserPasswordImportedEvent::class,
        'user.authentication.sso' => Event\UserAuth\OktaUserAuthSsoEvent::class,
        'app.user_management' => Event\AppUserManagement\OktaAppUserManagementImportEvent::class,
        'app.user_management.user_group_import.upsert_success' => Event\AppUserManagement\OktaAppUserGroupImportSuccessEvent::class,
        'resource.user_entitlements.update' => Event\EntitlementManagement\OktaResourceUserEntitlementsUpdatedEvent::class,
        'resource.entitlement_bundle.create' => Event\EntitlementManagement\OktaResourceEntitlementBundleCreatedEvent::class,
        'resource.entitlement_bundle.update' => Event\EntitlementManagement\OktaResourceEntitlementBundleUpdatedEvent::class,
        'resource.entitlement_bundle.delete' => Event\EntitlementManagement\OktaResourceEntitlementBundleDeletedEvent::class,
        'resource.entitlement.create' => Event\EntitlementManagement\OktaResourceEntitlementCreatedEvent::class,
        'resource.entitlement.update' => Event\EntitlementManagement\OktaResourceEntitlementUpdatedEvent::class,
        'resource.entitlement.delete' => Event\EntitlementManagement\OktaResourceEntitlementDeletedEvent::class,
        'resource.governance_engine.enable' => Event\EntitlementManagement\OktaGovernanceEngineEnabledEvent::class,
        'resource.governance_engine.disable' => Event\EntitlementManagement\OktaGovernanceEngineDisabledEvent::class,
        'resource.entitlement_policy.activate' => Event\EntitlementManagement\OktaEntitlementPolicyActivatedEvent::class,
        'resource.entitlement_policy.draft.create' => Event\EntitlementManagement\OktaEntitlementPolicyDraftCreatedEvent::class,
        'resource.entitlement_policy.draft.update' => Event\EntitlementManagement\OktaEntitlementPolicyDraftUpdatedEvent::class,
        'resource.entitlement_policy.draft.delete' => Event\EntitlementManagement\OktaEntitlementPolicyDraftDeletedEvent::class,
        'resource.collection.create' => Event\EntitlementManagement\OktaResourceCollectionCreatedEvent::class,
        'resource.collection.delete' => Event\EntitlementManagement\OktaResourceCollectionDeletedEvent::class,
        'resource.collection.update' => Event\EntitlementManagement\OktaResourceCollectionUpdatedEvent::class,
        'resource.collection.assign' => Event\EntitlementManagement\OktaResourceCollectionAssignedEvent::class,
        'resource.collection.unassign' => Event\EntitlementManagement\OktaResourceCollectionUnassignedEvent::class,
        'resource.risk_rule.create' => Event\EntitlementManagement\OktaRiskRuleCreatedEvent::class,
        'resource.risk_rule.update' => Event\EntitlementManagement\OktaRiskRuleUpdatedEvent::class,
        'resource.risk_rule.delete' => Event\EntitlementManagement\OktaRiskRuleDeletedEvent::class,
        'resource.owner.update' => Event\EntitlementManagement\OktaResourceOwnerUpdatedEvent::class,
        'resource.label.update' => Event\EntitlementManagement\OktaResourceLabelUpdatedEvent::class,
        'resource.label.assignment.update' => Event\EntitlementManagement\OktaResourceLabelAssignmentUpdatedEvent::class,
        'device.enrollment.create' => Event\DeviceIdentity\OktaDeviceEnrolledEvent::class,
        'device.lifecycle.delete' => Event\DeviceIdentity\OktaDeviceDeletedEvent::class,
        'device.lifecycle.activate' => Event\DeviceIdentity\OktaDeviceActivatedEvent::class,
        'device.lifecycle.deactivate' => Event\DeviceIdentity\OktaDeviceDeactivatedEvent::class,
        'device.lifecycle.suspend' => Event\DeviceIdentity\OktaDeviceSuspendedEvent::class,
        'device.lifecycle.unsuspend' => Event\DeviceIdentity\OktaDeviceUnsuspendedEvent::class,
        'device.user.add' => Event\DeviceIdentity\OktaDeviceUserAddedEvent::class,
        'device.user.remove' => Event\DeviceIdentity\OktaDeviceUserRemovedEvent::class,
        'system.email.delivery' => Event\EmailDelivery\OktaEmailDeliveryStatusUpdatedEvent::class,
        'access.review.create' => Event\AccessReview\OktaAccessReviewCreatedEvent::class,
        'access.review.start' => Event\AccessReview\OktaAccessReviewStartedEvent::class,
        'access.review.close' => Event\AccessReview\OktaAccessReviewClosedEvent::class,
        'access.review.update' => Event\AccessReview\OktaAccessReviewUpdatedEvent::class,
        'access.review.action' => Event\AccessReview\OktaAccessReviewActionEvent::class,
        'access.review.remediate' => Event\AccessReview\OktaAccessReviewRemediatedEvent::class,
        'iam.role.subscriptions.update' => Event\IamRoleSubscription\OktaIamRoleSubscriptionUpdatedEvent::class,
        'inline_hook.executed' => Event\InlineHook\OktaInlineHookExecutedEvent::class,
        'application.provision.group_push.mapping.update.or.delete.failed.with.error' => Event\GroupApp\OktaGroupPushMappingFailedEvent::class,
        'system.log_stream.lifecycle.create' => Event\LogStream\OktaLogStreamCreatedEvent::class,
        'system.log_stream.lifecycle.update' => Event\LogStream\OktaLogStreamUpdatedEvent::class,
        'system.log_stream.lifecycle.activate' => Event\LogStream\OktaLogStreamActivatedEvent::class,
        'system.log_stream.lifecycle.deactivate' => Event\LogStream\OktaLogStreamDeactivatedEvent::class,
        'system.log_stream.lifecycle.delete' => Event\LogStream\OktaLogStreamDeletedEvent::class,
        'policy.lifecycle.activate' => Event\Policy\OktaPolicyActivatedEvent::class,
        'policy.lifecycle.deactivate' => Event\Policy\OktaPolicyDeactivatedEvent::class,
        'policy.lifecycle.update' => Event\Policy\OktaPolicyUpdatedEvent::class,
        'policy.rule.add' => Event\Policy\OktaPolicyRuleAddedEvent::class,
        'policy.rule.update' => Event\Policy\OktaPolicyRuleUpdatedEvent::class,
        'policy.rule.activate' => Event\Policy\OktaPolicyRuleActivatedEvent::class,
        'policy.rule.deactivate' => Event\Policy\OktaPolicyRuleDeactivatedEvent::class,
        'policy.rule.delete' => Event\Policy\OktaPolicyRuleDeletedEvent::class,
        'app.oauth2.trusted_server.add' => Event\Policy\OktaTrustedServerAddedEvent::class,
        'app.oauth2.trusted_server.delete' => Event\Policy\OktaTrustedServerDeletedEvent::class,
        'security.trusted_origin.create' => Event\TrustedOrigin\OktaTrustedOriginCreatedEvent::class,
        'security.trusted_origin.update' => Event\TrustedOrigin\OktaTrustedOriginUpdatedEvent::class,
        'security.trusted_origin.delete' => Event\TrustedOrigin\OktaTrustedOriginDeletedEvent::class,
        'security.trusted_origin.activate' => Event\TrustedOrigin\OktaTrustedOriginActivatedEvent::class,
        'security.trusted_origin.deactivate' => Event\TrustedOrigin\OktaTrustedOriginDeactivatedEvent::class,
        'system.import.start' => Event\UserImport\OktaImportStartedEvent::class,
        'system.import.complete' => Event\UserImport\OktaImportCompletedEvent::class,
        'system.import.roadblock' => Event\UserImport\OktaImportRoadblockEvent::class,
        'governance.principal.settings.update' => Event\Governance\OktaGovernancePrincipalSettingsUpdatedEvent::class,
        'governance.settings.update' => Event\Governance\OktaGovernanceSettingsUpdatedEvent::class,
        'system.idp.lifecycle.create' => Event\IdpLifecycle\OktaIdpCreatedEvent::class,
        'system.idp.lifecycle.update' => Event\IdpLifecycle\OktaIdpUpdatedEvent::class,
        'system.idp.lifecycle.delete' => Event\IdpLifecycle\OktaIdpDeletedEvent::class,
        'system.idp.lifecycle.deactivate' => Event\IdpLifecycle\OktaIdpDeactivatedEvent::class,
        'system.idp.lifecycle.activate' => Event\IdpLifecycle\OktaIdpActivatedEvent::class,
        'system.idp.lifecycle.read_client_secret' => Event\IdpLifecycle\OktaIdpClientSecretReadEvent::class,
        'app.ad.password_migration_campaign.user.migrate.end' => Event\PasswordMigration\OktaPasswordMigrationCompletedEvent::class,
        'security.authenticator.lifecycle.create' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorCreatedEvent::class,
        'security.authenticator.lifecycle.update' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorUpdatedEvent::class,
        'security.authenticator.lifecycle.activate' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorActivatedEvent::class,
        'security.authenticator.lifecycle.deactivate' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorDeactivatedEvent::class,
        'system.api_token.request_outside_allowed_range' => Event\Security\OktaApiTokenOutsideAllowedRangeEvent::class,
        'user.account.report_suspicious_activity_by_enduser' => Event\Security\OktaUserSuspiciousActivityReportedEvent::class,
        'security.breached_credential.detected' => Event\Security\OktaBreachedCredentialDetectedEvent::class,
        'user.risk.change' => Event\Security\OktaUserRiskChangedEvent::class,
        'user.risk.detect' => Event\Security\OktaUserRiskDetectedEvent::class,
        'user.behavior.profile.reset' => Event\Security\OktaUserBehaviorProfileResetEvent::class,
        'policy.auth_reevaluate.fail' => Event\Security\OktaPolicyAuthReevaluationFailedEvent::class,
        'user.session.context.change' => Event\Security\OktaUserSessionContextChangedEvent::class,
        'system.oauth2.token.request_outside_allowed_range' => Event\Security\OktaOAuth2TokenOutsideAllowedRangeEvent::class,
        'user.authentication.authenticate' => Event\DeviceTrust\OktaDeviceTrustAuthenticatedEvent::class,
        'user.credential.enroll' => Event\DeviceTrust\OktaDeviceTrustCredentialEnrolledEvent::class,
    ];

    /**
     * Maps Okta event type IDs to their group event class.
     * Every known Okta event type has a group mapping, including those already
     * handled by OktaEventMapper (e.g. user.lifecycle.*, group.user_membership.*,
     * application.user_membership.*) — the controller dispatches both the typed
     * event from the mapper AND the group event from this registry.
     *
     * @var array<string, class-string<GenericOktaEvent>>
     */
    private const GROUP_EVENTS = [
        'access.request.create' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.resolve' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.cancel' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.expire' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.reject' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.sequence.create' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.sequence.update' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.sequence.delete' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.create' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.update' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.delete' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.activate' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.deactivate' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.condition.invalidate' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'access.request.settings.update' => Event\AccessRequest\OktaAccessRequestEvent::class,
        'system.idp.key.create' => Event\IdpKey\OktaIdpKeyEvent::class,
        'system.idp.key.update' => Event\IdpKey\OktaIdpKeyEvent::class,
        'system.idp.key.delete' => Event\IdpKey\OktaIdpKeyEvent::class,
        'user.account.subscriptions.update' => Event\UserAccountSubscription\OktaUserAccountSubscriptionEvent::class,
        'application.lifecycle.activate' => Event\ApplicationLifecycle\OktaApplicationLifecycleEvent::class,
        'application.lifecycle.create' => Event\ApplicationLifecycle\OktaApplicationLifecycleEvent::class,
        'application.lifecycle.deactivate' => Event\ApplicationLifecycle\OktaApplicationLifecycleEvent::class,
        'application.lifecycle.delete' => Event\ApplicationLifecycle\OktaApplicationLifecycleEvent::class,
        'application.lifecycle.update' => Event\ApplicationLifecycle\OktaApplicationLifecycleEvent::class,
        'group.lifecycle.create' => Event\GroupLifecycle\OktaGroupLifecycleEvent::class,
        'group.lifecycle.delete' => Event\GroupLifecycle\OktaGroupLifecycleEvent::class,
        'system.import.group.create' => Event\GroupLifecycle\OktaGroupLifecycleEvent::class,
        'system.import.group.delete' => Event\GroupLifecycle\OktaGroupLifecycleEvent::class,
        'certification.campaign.launch' => Event\Certification\OktaCertificationEvent::class,
        'certification.campaign.close' => Event\Certification\OktaCertificationEvent::class,
        'certification.campaign.item.decide' => Event\Certification\OktaCertificationEvent::class,
        'certification.campaign.item.remediate' => Event\Certification\OktaCertificationEvent::class,
        'certification.campaign.context.update' => Event\Certification\OktaCertificationEvent::class,
        'group.user_membership.add' => Event\Group\OktaGroupEvent::class,
        'group.user_membership.remove' => Event\Group\OktaGroupEvent::class,
        'group.profile.update' => Event\Group\OktaGroupEvent::class,
        'group.application_assignment.remove' => Event\Group\OktaGroupEvent::class,
        'group.application_assignment.add' => Event\Group\OktaGroupEvent::class,
        'group.application_assignment.update' => Event\Group\OktaGroupEvent::class,
        'system.org.rate_limit.warning' => Event\RateLimit\OktaRateLimitEvent::class,
        'system.org.rate_limit.violation' => Event\RateLimit\OktaRateLimitEvent::class,
        'application.user_membership.add' => Event\UserApp\OktaUserAppEvent::class,
        'application.user_membership.remove' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.request' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.approver.approve' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.approver.deny' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.expire' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.delete' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.grant' => Event\UserApp\OktaUserAppEvent::class,
        'app.access_request.deny' => Event\UserApp\OktaUserAppEvent::class,
        'application.user_membership.change_password' => Event\UserApp\OktaUserAppEvent::class,
        'application.user_membership.update' => Event\UserApp\OktaUserAppEvent::class,
        'application.provision.user.sync' => Event\UserApp\OktaUserAppEvent::class,
        'application.provision.user.import_profile' => Event\UserApp\OktaUserAppEvent::class,
        'application.provision.user.push' => Event\UserApp\OktaUserAppEvent::class,
        'application.provision.user.push_profile' => Event\UserApp\OktaUserAppEvent::class,
        'application.provision.user.reactivate' => Event\UserApp\OktaUserAppEvent::class,
        'app.interclient_mapping.create' => Event\UserApp\OktaUserAppEvent::class,
        'app.interclient_mapping.delete' => Event\UserApp\OktaUserAppEvent::class,
        'app.interclient_mapping.delete_all' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.grant' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.implicit.as' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.implicit.client' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.implicit.scope' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.implicit.user' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.user' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.consent.revoke.user.client' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.as.token.grant.interclient_token' => Event\UserApp\OktaUserAppEvent::class,
        'app.oauth2.token.grant.interclient_token' => Event\UserApp\OktaUserAppEvent::class,
        'entitlement.migration.start' => Event\EntitlementMigration\OktaEntitlementMigrationEvent::class,
        'entitlement.migration.complete' => Event\EntitlementMigration\OktaEntitlementMigrationEvent::class,
        'entitlement.migration.fail' => Event\EntitlementMigration\OktaEntitlementMigrationEvent::class,
        'user.account.privilege.grant' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'user.account.privilege.revoke' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'group.privilege.grant' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'group.privilege.revoke' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'app.oauth2.client.privilege.grant' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'app.oauth2.client.privilege.revoke' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.create' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.update' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.permissions.add' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.permissions.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.permission.conditions.add' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.role.permission.conditions.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.create' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.update' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.resources.add' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.resources.update' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.resources.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.bindings.add' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.resourceset.bindings.delete' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.policy.configuration.update' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'iam.policy.assignee_configuration.update' => Event\AdminPrivilege\OktaAdminPrivilegeEvent::class,
        'system.api_token.create' => Event\UserAuth\OktaUserAuthEvent::class,
        'system.api_token.revoke' => Event\UserAuth\OktaUserAuthEvent::class,
        'system.voice.send_phone_verification_call' => Event\UserAuth\OktaUserAuthEvent::class,
        'system.mfa.preregister.initiate' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.auth_via_mfa' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.activate' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.deactivate' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.suspend' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.unsuspend' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.update' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.mfa.factor.reset_all' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.session.clear' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.account.reset_password' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.account.unlock' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.account.unlock_by_admin' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.account.update_password' => Event\UserAuth\OktaUserAuthEvent::class,
        'application.policy.sign_on.deny_access' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.auth_via_IDP' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.auth_via_social' => Event\UserAuth\OktaUserAuthEvent::class,
        'system.sms.send_phone_verification_message' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.session.start' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.session.end' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.universal_logout' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.universal_logout.scheduled' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.account.lock' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.identity_verification' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.identity_verification.start' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.import.password' => Event\UserAuth\OktaUserAuthEvent::class,
        'user.authentication.sso' => Event\UserAuth\OktaUserAuthEvent::class,
        'app.user_management' => Event\AppUserManagement\OktaAppUserManagementEvent::class,
        'app.user_management.user_group_import.upsert_success' => Event\AppUserManagement\OktaAppUserManagementEvent::class,
        'resource.user_entitlements.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_bundle.create' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_bundle.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_bundle.delete' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement.create' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement.delete' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.governance_engine.enable' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.governance_engine.disable' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_policy.activate' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_policy.draft.create' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_policy.draft.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.entitlement_policy.draft.delete' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.collection.create' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.collection.delete' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.collection.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.collection.assign' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.collection.unassign' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.risk_rule.create' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.risk_rule.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.risk_rule.delete' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.owner.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.label.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'resource.label.assignment.update' => Event\EntitlementManagement\OktaEntitlementManagementEvent::class,
        'device.enrollment.create' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.lifecycle.delete' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.lifecycle.activate' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.lifecycle.deactivate' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.lifecycle.suspend' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.lifecycle.unsuspend' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.user.add' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'device.user.remove' => Event\DeviceIdentity\OktaDeviceIdentityEvent::class,
        'system.email.delivery' => Event\EmailDelivery\OktaEmailDeliveryEvent::class,
        'access.review.create' => Event\AccessReview\OktaAccessReviewEvent::class,
        'access.review.start' => Event\AccessReview\OktaAccessReviewEvent::class,
        'access.review.close' => Event\AccessReview\OktaAccessReviewEvent::class,
        'access.review.update' => Event\AccessReview\OktaAccessReviewEvent::class,
        'access.review.action' => Event\AccessReview\OktaAccessReviewEvent::class,
        'access.review.remediate' => Event\AccessReview\OktaAccessReviewEvent::class,
        'iam.role.subscriptions.update' => Event\IamRoleSubscription\OktaIamRoleSubscriptionEvent::class,
        'inline_hook.executed' => Event\InlineHook\OktaInlineHookEvent::class,
        'application.provision.group_push.mapping.update.or.delete.failed.with.error' => Event\GroupApp\OktaGroupAppEvent::class,
        'system.log_stream.lifecycle.create' => Event\LogStream\OktaLogStreamEvent::class,
        'system.log_stream.lifecycle.update' => Event\LogStream\OktaLogStreamEvent::class,
        'system.log_stream.lifecycle.activate' => Event\LogStream\OktaLogStreamEvent::class,
        'system.log_stream.lifecycle.deactivate' => Event\LogStream\OktaLogStreamEvent::class,
        'system.log_stream.lifecycle.delete' => Event\LogStream\OktaLogStreamEvent::class,
        'policy.lifecycle.activate' => Event\Policy\OktaPolicyEvent::class,
        'policy.lifecycle.deactivate' => Event\Policy\OktaPolicyEvent::class,
        'policy.lifecycle.update' => Event\Policy\OktaPolicyEvent::class,
        'policy.rule.add' => Event\Policy\OktaPolicyEvent::class,
        'policy.rule.update' => Event\Policy\OktaPolicyEvent::class,
        'policy.rule.activate' => Event\Policy\OktaPolicyEvent::class,
        'policy.rule.deactivate' => Event\Policy\OktaPolicyEvent::class,
        'policy.rule.delete' => Event\Policy\OktaPolicyEvent::class,
        'app.oauth2.trusted_server.add' => Event\Policy\OktaPolicyEvent::class,
        'app.oauth2.trusted_server.delete' => Event\Policy\OktaPolicyEvent::class,
        'security.trusted_origin.create' => Event\TrustedOrigin\OktaTrustedOriginEvent::class,
        'security.trusted_origin.update' => Event\TrustedOrigin\OktaTrustedOriginEvent::class,
        'security.trusted_origin.delete' => Event\TrustedOrigin\OktaTrustedOriginEvent::class,
        'security.trusted_origin.activate' => Event\TrustedOrigin\OktaTrustedOriginEvent::class,
        'security.trusted_origin.deactivate' => Event\TrustedOrigin\OktaTrustedOriginEvent::class,
        'system.import.start' => Event\UserImport\OktaUserImportEvent::class,
        'system.import.complete' => Event\UserImport\OktaUserImportEvent::class,
        'system.import.roadblock' => Event\UserImport\OktaUserImportEvent::class,
        'user.account.update_profile' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.deactivate' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.create' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.activate' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.reactivate' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.suspend' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.unsuspend' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'user.lifecycle.delete.initiated' => Event\UserLifecycle\OktaUserLifecycleGroupEvent::class,
        'governance.principal.settings.update' => Event\Governance\OktaGovernanceEvent::class,
        'governance.settings.update' => Event\Governance\OktaGovernanceEvent::class,
        'system.idp.lifecycle.create' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'system.idp.lifecycle.update' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'system.idp.lifecycle.delete' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'system.idp.lifecycle.deactivate' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'system.idp.lifecycle.activate' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'system.idp.lifecycle.read_client_secret' => Event\IdpLifecycle\OktaIdpLifecycleEvent::class,
        'app.ad.password_migration_campaign.user.migrate.end' => Event\PasswordMigration\OktaPasswordMigrationEvent::class,
        'security.authenticator.lifecycle.create' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorEvent::class,
        'security.authenticator.lifecycle.update' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorEvent::class,
        'security.authenticator.lifecycle.activate' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorEvent::class,
        'security.authenticator.lifecycle.deactivate' => Event\SecurityAuthenticator\OktaSecurityAuthenticatorEvent::class,
        'system.api_token.request_outside_allowed_range' => Event\Security\OktaSecurityEvent::class,
        'user.account.report_suspicious_activity_by_enduser' => Event\Security\OktaSecurityEvent::class,
        'security.breached_credential.detected' => Event\Security\OktaSecurityEvent::class,
        'user.risk.change' => Event\Security\OktaSecurityEvent::class,
        'user.risk.detect' => Event\Security\OktaSecurityEvent::class,
        'user.behavior.profile.reset' => Event\Security\OktaSecurityEvent::class,
        'policy.auth_reevaluate.fail' => Event\Security\OktaSecurityEvent::class,
        'user.session.context.change' => Event\Security\OktaSecurityEvent::class,
        'system.oauth2.token.request_outside_allowed_range' => Event\Security\OktaSecurityEvent::class,
        'user.authentication.authenticate' => Event\DeviceTrust\OktaDeviceTrustEvent::class,
        'user.credential.enroll' => Event\DeviceTrust\OktaDeviceTrustEvent::class,
    ];

    /**
     * Returns the individual event class for a given Okta event type, or null if not mapped.
     *
     * @return class-string<GenericOktaEvent>|null
     */
    public function getIndividualEventClass(string $eventType): ?string
    {
        return self::INDIVIDUAL_EVENTS[$eventType] ?? null;
    }

    /**
     * Returns the group event class for a given Okta event type, or null if not mapped.
     *
     * @return class-string<GenericOktaEvent>|null
     */
    public function getGroupEventClass(string $eventType): ?string
    {
        return self::GROUP_EVENTS[$eventType] ?? null;
    }

    /**
     * Creates an individual event instance for the given OktaEvent DTO.
     */
    public function createIndividualEvent(OktaEvent $oktaEvent): ?GenericOktaEvent
    {
        $class = $this->getIndividualEventClass($oktaEvent->eventType);

        if (null === $class) {
            return null;
        }

        return new $class($oktaEvent);
    }

    /**
     * Creates a group event instance for the given OktaEvent DTO.
     */
    public function createGroupEvent(OktaEvent $oktaEvent): ?GenericOktaEvent
    {
        $class = $this->getGroupEventClass($oktaEvent->eventType);

        if (null === $class) {
            return null;
        }

        return new $class($oktaEvent);
    }
}
